import { Machine, MachineProps } from "../../../domain/entities/Machine";
import { IMachineRepository } from "../../../domain/repositories/IMachineRepository";
import { CreateMachineDto } from "../../dto/requests/CreateMachineDto";

export class CreateMachineUseCase {
  constructor(private machineRepository: IMachineRepository) {}

  async execute(machineData: CreateMachineDto): Promise<Machine> {
    const machineProps: MachineProps = {
      id: "", // Will be generated by database
      machineId: machineData.machineId,
      serialNumber: machineData.serialNumber,
      room: machineData.room,
      status: machineData.status,
      lastMaintenanceDate: machineData.lastMaintenanceDate,
      nextMaintenanceDate: machineData.nextMaintenanceDate
    };

    const machine = new Machine(machineProps);
    return await this.machineRepository.createMachine(machine);
  }
}